import Head from "next/head";
import Filters from "../components/filters";
import ResultList from "../components/resultlist";

export default function Home() {
  return (
    <>
      <Head>
        <title>Alculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1 className="col center text-center">Alculator</h1>
        <Filters />
        <ResultList />
      </main>
    </>
  );
}
